import { DecisionEntry } from "./decisionEntryTypes";

export function renderDecisionDossierHtml(entry: DecisionEntry): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Decision Dossier – ${entry.title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, Inter, Segoe UI, Roboto, sans-serif;
      margin: 40px;
      color: #0b0f14;
      background: #ffffff;
    }
    h1 {
      font-size: 28px;
      margin-bottom: 8px;
    }
    .meta {
      color: #666;
      font-size: 13px;
      margin-bottom: 24px;
    }
    .footer {
      margin-top: 48px;
      font-size: 11px;
      color: #888;
      text-align: center;
    }
  </style>
</head>
<body>
  <h1>${entry.title}</h1>

  <div class="meta">
    Decision ID: ${entry.id}<br/>
    Created: ${new Date(entry.createdAt).toLocaleString()}
  </div>

  <div class="footer">
    Generated by Digital Hooligan · Decision Dossier Export
  </div>
</body>
</html>
`;
}
