export interface DecisionDossierExport {
  id: string;
  title: string;
  createdAt: string;
}

export function renderDecisionDossierHtml(
  decision: DecisionDossierExport
): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Decision Dossier — ${decision.title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, Inter, Segoe UI, Roboto, sans-serif;
      margin: 40px;
      color: #0b0f14;
      background: #ffffff;
    }
    h1 {
      font-size: 28px;
      margin-bottom: 8px;
    }
    .meta {
      color: #666;
      font-size: 13px;
      margin-bottom: 24px;
    }
    footer {
      margin-top: 48px;
      font-size: 11px;
      color: #888;
      text-align: center;
    }
  </style>
</head>
<body>
  <h1>${decision.title}</h1>

  <div class="meta">
    Decision ID: ${decision.id}<br/>
    Created: ${new Date(decision.createdAt).toLocaleString()}
  </div>

  <footer>
    Generated by Digital Hooligan — Decision Dossier Export
  </footer>
</body>
</html>
`;
}
