name: Feature request
description: Suggest an idea
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What outcome do we want?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What is in/out?
    validations:
      required: true
